[project]
name = "billigaste-kvittot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.11",
    "dlt>=1.18.2",
    "dotenv>=0.9.9",
    "duckdb>=1.4.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
